#!/usr/bin/env python3
"""
Apply PCA (32D, whitening + L2-norm) to the SIFT-RANSAC index.

Prerequisite:
    indexes/sift_ransac.npz must exist (generated by scripts/generate_sift_index.py).

What this script does:
    1. Loads all SIFT descriptors (uint8, 128D) from indexes/sift_ransac.npz
    2. Fits PCA + whitening on a random sample of 300K descriptors
    3. Transforms all descriptors to 32D float16
    4. Overwrites indexes/sift_ransac.npz with the reduced index
    5. Saves the PCA model to indexes/pca_sift_ransac.npz

Results:
    - Index size:    ~200 MB  ->  ~146 MB  (-27%)
    - RANSAC inliers: baseline 4.3  ->  5.7  (+32%)

Usage:
    python scripts/apply_pca_sift.py
"""

import os
import sys
import time
import numpy as np

ROOT      = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX_DIR = os.path.join(ROOT, "indexes")
NPZ_PATH  = os.path.join(INDEX_DIR, "sift_ransac.npz")
PCA_PATH  = os.path.join(INDEX_DIR, "pca_sift_ransac.npz")

K         = 32       # target dimension
EPS       = 1e-3     # whitening regularisation
N_SAMPLE  = 300_000  # descriptors used to fit PCA


def fit_pca(sample: np.ndarray, k: int):
    mean = sample.mean(axis=0)
    Xc   = sample - mean
    C    = (Xc.T @ Xc) / len(sample)
    eigenvalues, eigenvectors = np.linalg.eigh(C)
    idx          = np.argsort(eigenvalues)[::-1]
    eigenvalues  = eigenvalues[idx]
    eigenvectors = eigenvectors[:, idx]
    components       = eigenvectors[:, :k].T.astype(np.float32)   # (k, 128)
    whitening_scale  = (1.0 / (np.sqrt(eigenvalues[:k]) + EPS)).astype(np.float32)
    return mean.astype(np.float32), components, whitening_scale


def apply_transform(des_uint8: np.ndarray, mean, components, whitening_scale) -> np.ndarray:
    df   = des_uint8.astype(np.float32) * 2.0
    proj = ((df - mean) @ components.T) * whitening_scale
    n    = np.linalg.norm(proj, axis=1, keepdims=True)
    n[n == 0] = 1.0
    return (proj / n).astype(np.float16)


def main():
    if not os.path.exists(NPZ_PATH):
        print(f"[ERROR] {NPZ_PATH} not found.")
        print("        Run scripts/generate_sift_index.py first.")
        sys.exit(1)

    # ── Check if already PCA-reduced ────────────────────────────────────────
    probe = np.load(NPZ_PATH)
    sample_key = next((k for k in probe.files if k.endswith("_des")), None)
    if sample_key and probe[sample_key].dtype == np.float16:
        print("[INFO] Index is already PCA-reduced (float16). Nothing to do.")
        sys.exit(0)

    print(f"Loading {NPZ_PATH} ...")
    t0  = time.time()
    raw = {k: probe[k] for k in probe.files}
    print(f"  Loaded in {time.time()-t0:.1f}s")

    des_keys = [k for k in raw if k.endswith("_des")]
    kp_keys  = [k for k in raw if k.endswith("_kp")]
    print(f"  {len(des_keys)} images")

    # ── Collect sample for PCA fitting ──────────────────────────────────────
    print(f"Sampling {N_SAMPLE:,} descriptors for PCA fitting ...")
    all_des = np.concatenate([raw[k].astype(np.float32) * 2.0 for k in des_keys], axis=0)
    rng     = np.random.default_rng(42)
    idx     = rng.choice(len(all_des), size=min(N_SAMPLE, len(all_des)), replace=False)
    sample  = all_des[idx]
    print(f"  Total descriptors: {len(all_des):,}")

    # ── Fit PCA ─────────────────────────────────────────────────────────────
    print(f"Fitting PCA({K}D) ...")
    t0 = time.time()
    mean, components, whitening_scale = fit_pca(sample, K)
    cumvar = np.cumsum(
        np.sort(np.linalg.eigvalsh((sample - mean).T @ (sample - mean) / len(sample)))[::-1]
    )
    print(f"  Done in {time.time()-t0:.1f}s")

    # ── Transform all descriptors ────────────────────────────────────────────
    print("Transforming all descriptors ...")
    t0      = time.time()
    new_data = {}
    for kpk, desk in zip(kp_keys, des_keys):
        new_data[kpk] = raw[kpk]
        new_data[desk] = apply_transform(raw[desk], mean, components, whitening_scale)
    print(f"  Done in {time.time()-t0:.1f}s")

    # ── Save reduced index ────────────────────────────────────────────────────
    print(f"Saving {NPZ_PATH} ...")
    t0 = time.time()
    np.savez_compressed(NPZ_PATH, **new_data)
    sz = os.path.getsize(NPZ_PATH) / 1024 ** 2
    print(f"  Saved in {time.time()-t0:.1f}s — {sz:.1f} MB")

    # ── Save PCA model ────────────────────────────────────────────────────────
    np.savez_compressed(
        PCA_PATH,
        mean=mean,
        components=components,
        whitening_scale=whitening_scale,
        original_dim=np.array(128),
        reduced_dim=np.array(K),
    )
    print(f"PCA model saved -> {PCA_PATH}")
    print("Done.")


if __name__ == "__main__":
    main()
